apiVersion: v1
kind: Pod
metadata:
  name: runc-webserver
  labels:
    app: runc-webserver
  namespace: kata-sysinfo
spec:
  containers:
    - name: runc-webserver
      image: quay.io/bpradipt/sysinfo
      ports:
        - containerPort: 80

---

kind: Service
apiVersion: v1
metadata:
  name: runc-webserver-service
  namespace: kata-sysinfo
spec:
  selector:
    app: runc-webserver
  ports:
    - port: 80

---

kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: runc-webserver-route
  namespace: kata-sysinfo
spec:
  to:
    kind: Service
    name: runc-webserver-service
  tls:
     termination: edge
