apiVersion: v1
kind: Namespace
metadata:
  name: web-sample
---

apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: echo-kata
    name: echo-kata
    namespace: web-sample
spec:
    replicas: 1
    selector:
        matchLabels:
            app: echo-kata
    template:
        metadata:
            labels:
                app: echo-kata
        spec:
          containers:
            - name: echo-kata
              image: quay.io/bpradipt/http-echo
              args: [ "-text", "Hello from Kata container", "-listen", ":8080"]
          runtimeClassName: kata
---

kind: Service
apiVersion: v1
metadata:
 name: echo-kata
 namespace: web-sample
spec:
 selector:
   app: echo-kata
 ports:
   - port: 8080

---

kind: Route
apiVersion: route.openshift.io/v1
metadata:
 name: echo-route
 namespace: web-sample
spec:
 to:
   kind: Service
   name: echo-kata
   weight: 100
 tls:
    termination: edge
