apiVersion: v1
kind: Pod
metadata:
  name: buildah
  namespace: kata-builds
spec:
  runtimeClassName: kata
  containers:
    - name: buildah
      image: quay.io/buildah/stable:v1.14.8
      command: ["sleep", "infinity"]

