apiVersion: v1
kind: Pod
metadata:
 name: echo-debug
 labels:
   app: echo-debug
 namespace: sample
spec:
 containers:
   - name: echo-debug
     image: quay.io/bpradipt/http-echo
     args: [ "-text", "Hello from Runc debug container", "-listen", ":8080"]
   - name: perf-sidecar
     image: quay.io/bpradipt/perf-amd64:latest
     imagePullPolicy: IfNotPresent
     volumeMounts:
     - name: perf-output
       mountPath: /out
     securityContext:
       privileged: true
 volumes:
     - name: perf-output
       hostPath:
          path: /run/out
          type: DirectoryOrCreate
 ShareProcessNamespace: true  
---
 
kind: Service
apiVersion: v1
metadata:
 name: echo-debug
 namespace: sample
spec:
 selector:
   app: echo-debug
 ports:
   - port: 8080

